name: flutter_hw1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^0.20.1 # 更新 audioplayers 依賴版本

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/chan.png
    - assets/leeknow.png
    - assets/bin.png
    - assets/jin.png
    - assets/han.png
    - assets/felix.png
    - assets/puppym.png
    - assets/in.png
    - assets/sounds/jump.mp3
    - assets/sounds/game_over.mp3

  fonts:
    - family: crayon
      fonts:
        - asset: fonts/crayon_1-1.ttf
